# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0010_auto_20151020_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='admin_leve',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='aeroway',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='building',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='craft',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='geological',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='historic',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='landuse',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='leisure',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='man_made',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='military',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='name',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='natural',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='office',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='osm_id',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='osm_way_id',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='other_tags',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='place',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='tourism',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='type',
        ),
        migrations.RemoveField(
            model_name='lines',
            name='aerialway',
        ),
        migrations.RemoveField(
            model_name='lines',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='lines',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='lines',
            name='highway',
        ),
        migrations.RemoveField(
            model_name='lines',
            name='man_made',
        ),
        migrations.RemoveField(
            model_name='lines',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lines',
            name='osm_id',
        ),
        migrations.RemoveField(
            model_name='lines',
            name='other_tags',
        ),
        migrations.RemoveField(
            model_name='lines',
            name='waterway',
        ),
        migrations.RemoveField(
            model_name='multilinestrings',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='multilinestrings',
            name='name',
        ),
        migrations.RemoveField(
            model_name='multilinestrings',
            name='osm_id',
        ),
        migrations.RemoveField(
            model_name='multilinestrings',
            name='other_tags',
        ),
        migrations.RemoveField(
            model_name='multilinestrings',
            name='type',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='admin_leve',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='aeroway',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='boundary',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='building',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='craft',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='geological',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='historic',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='landuse',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='leisure',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='man_made',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='military',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='name',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='natural',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='office',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='osm_id',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='osm_way_id',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='other_tags',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='place',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='tourism',
        ),
        migrations.RemoveField(
            model_name='multipolygons',
            name='type',
        ),
        migrations.RemoveField(
            model_name='points',
            name='address',
        ),
        migrations.RemoveField(
            model_name='points',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='points',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='points',
            name='highway',
        ),
        migrations.RemoveField(
            model_name='points',
            name='is_in',
        ),
        migrations.RemoveField(
            model_name='points',
            name='man_made',
        ),
        migrations.RemoveField(
            model_name='points',
            name='name',
        ),
        migrations.RemoveField(
            model_name='points',
            name='osm_id',
        ),
        migrations.RemoveField(
            model_name='points',
            name='other_tags',
        ),
        migrations.RemoveField(
            model_name='points',
            name='place',
        ),
        migrations.RemoveField(
            model_name='points',
            name='ref',
        ),
    ]
